zookeeper1:
    image: wurstmeister/zookeeper
    ports:
     - "2181:2181"
    environment:
     - KAFKA_ADVERTISED_HOST_NAME=zookeeper1
    extra_hosts:
      zookeeper1: $ZOOKEEPER_IP
  kafka1:
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
     - "9092:9092"
    environment:
     - KAFKA_ADVERTISED_PORT=9092
     - KAFKA_ADVERTISED_HOST_NAME=zookeeper1
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper1:2181
    extra_hosts:
      zookeeper1: $ZOOKEEPER_IP
    depends_on:
     - zookeeper1
config-service:
  image: microservice/config-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
  ports:
   - 8888:8888
hystrix-dashboard:
  image: microservice/hystrix-dashboard
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
  ports:
   - 6161:6161
mysql:
  image: mysql:5.7
  ports:
   - 3306:3306
  environment:
   - MYSQL_ROOT_PASSWORD=dbpass
   - MYSQL_DATABASE=dev
redis:
  image: redis:3.0
  ports:
   - 6379:6379
discovery-service:
  image: microservice/discovery-service
  ports:
   - 8761:8761
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
inventory-service:
  image: microservice/inventory-service
  ports:
     - 8082:8082
  links:
   - redis
   - mysql
   - discovery-service
   - config-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
catalog-service:
  image: microservice/catalog-service
  ports:
     - 8083:8083
  links:
   - redis
   - mysql
   - discovery-service
   - config-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
price-service:
  image: microservice/price-service
  ports:
     - 8081:8081
  links:
   - redis
   - mysql
   - discovery-service
   - config-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP
web-storefront:
  image: microservice/web-storefront
  ports:
     - 8090:90
  links:
   - redis
   - mysql
   - discovery-service
   - config-service
  environment:
   - SPRING_PROFILES_ACTIVE=docker
   - DOCKER_IP=$DOCKER_IP