version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
  logstash:
    image: docker.elastic.co/logstash/logstash:5.5.1
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - $PWD/logstash/conf.d:/etc/logstash/conf.d
      - $PWD/log:/tmp
    hostname: logstash
    depends_on:
      - elasticsearch
    extra_hosts:
      elasticsearch: $DOCKER_IP
    ports:
      - "7001-7005:7001-7005"
      - "4567:4567"
    restart: always
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.1
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    hostname: kibana
    depends_on:
      - elasticsearch
    restart: always
    ports:
      - "5601:5601"
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    ports:
     - "9092:9092"
    environment:
     - KAFKA_ADVERTISED_PORT=9092
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
     - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
     - "2181:2181"
    environment:
     - KAFKA_ADVERTISED_HOST_NAME=zookeeper
  config-service:
    image: microservice/config-service
    environment:
     - DOCKER_IP=$DOCKER_IP
    ports:
     - 8888:8888
    restart: always
  hystrix-dashboard:
    image: microservice/hystrix-dashboard
    environment:
     - DOCKER_IP=$DOCKER_IP
    ports:
     - 6161:6161
    restart: always
  mysql:
    image: mysql:5.7
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=microservice
  redis:
    image: redis:3.0
    ports:
     - 6379:6379
    command: redis-server --requirepass admin123
  discovery-service:
    image: microservice/discovery-service
    ports:
     - 8761:8761
    environment:
     - DOCKER_IP=$DOCKER_IP
    restart: always
  upm-service:
    image: microservice/upm-service
    ports:
       - 8081:8081
    links:
     - redis
     - mysql
     - discovery-service
     - config-service
    environment:
     - DOCKER_IP=$DOCKER_IP
    extra_hosts:
      logstash: $DOCKER_IP
    restart: always