version: '2'
services:
  kafka:
    image: wurstmeister/kafka:0.11.0.1
    ports:
     - "9092:9092"
    environment:
     - KAFKA_ADVERTISED_PORT=9092
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
     - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
     - "2181:2181"
    environment:
     - KAFKA_ADVERTISED_HOST_NAME=zookeeper
  config-service:
    image: microservice/config-service
    environment:
     - DOCKER_IP=$DOCKER_IP
    ports:
     - 8888:8888
  hystrix-dashboard:
    image: microservice/hystrix-dashboard
    environment:
     - DOCKER_IP=$DOCKER_IP
    ports:
     - 6161:6161
  mysql:
    image: mysql:5.7
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=password
  redis:
    image: redis:3.0
    ports:
     - 6379:6379
  discovery-service:
    image: microservice/discovery-service
    ports:
     - 8761:8761
    environment:
     - DOCKER_IP=$DOCKER_IP
  inventory-service:
    image: microservice/inventory-service
    ports:
       - 8082:8082
    links:
     - redis
     - mysql
     - discovery-service
     - config-service
    environment:
     - DOCKER_IP=$DOCKER_IP
  price-service:
    image: microservice/price-service
    ports:
       - 8081:8081
    links:
     - redis
     - mysql
     - discovery-service
     - config-service
    environment:
     - DOCKER_IP=$DOCKER_IP
  web-storefront:
    image: microservice/web-storefront
    ports:
       - 8090:8090
    links:
     - redis
     - mysql
     - discovery-service
     - config-service
    environment:
     - DOCKER_IP=$DOCKER_IP