management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream,bus-refresh,info,health,routes
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
          zkNodes: zookeeper:2181