spring:
  datasource:
    url: jdbc:mysql://mysql:3306/microservice?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update