server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/microservice?useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    database: 0
    host: redis
    port: 6379
    password: admin123
    jedis:
      pool:
        max-wait: 1
        min-idle: 0
        max-idle: 8
    timeout: 0
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/