
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
# To disable Hystrix in Feign
  hystrix:
    enabled: false

# To set thread isolation to SEMAPHORE
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
#database
spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    url: jdbc:mysql://localhost:3306/microservice?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:/mybatis/*Mapper.xml
  type-aliases-package: com.aaxon.domain

pagehelper:
  support-methods-arguments: true
  params: pageNum=page

loginUsername: admin
loginPassword: admin