server:
  port: 8090
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/microservice
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

categoryIds: A,B,C,D
maxProductCoundInCategory: 800000
checkProductExistBeforeAdding: false